name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  test:
    name: Lint, Type-check & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          pixi-version: v0.41.4
          cache: true

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Install npm dependencies
        run: npm ci

      - name: Run core CI checks
        run: pixi run npm run verify:ci:core

  browser:
    name: Browser end-to-end tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Install npm dependencies
        run: npm ci

      - name: Install Chromium
        run: npx playwright install --with-deps chromium

      - name: Browser tests
        run: npm run verify:ci:browser
